# Generated by Django 4.2.21 on 2025-06-04 01:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(help_text='Nome completo do usuário.', max_length=255)),
                ('cpf', models.CharField(help_text='CPF do usuário (apenas números).', max_length=11, unique=True)),
                ('total_tokens_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total de tokens ganhos pelo usuário desde o cadastro.', max_digits=20)),
                ('tokens_balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo de tokens disponíveis para saque (simulado off-chain).', max_digits=20)),
                ('completed_missions', models.PositiveIntegerField(default=0, help_text='Quantidade de missões concluídas pelo usuário.')),
                ('withdrawal_minimum', models.DecimalField(decimal_places=2, default=10.0, help_text='Valor mínimo para saque.', max_digits=5)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('commercial_name', models.CharField(help_text='Nome fantasia da empresa.', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ da empresa (apenas números).', max_length=14, unique=True)),
                ('website', models.URLField(blank=True, help_text='URL do site oficial da empresa.')),
                ('logo_url', models.URLField(blank=True, help_text='URL da logo da empresa.')),
                ('verified', models.BooleanField(default=False, help_text='Indica se a empresa foi verificada pela plataforma.')),
                ('tokens_balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo de tokens disponível para ações internas da empresa (off-chain).', max_digits=20)),
                ('corporate_tax_id', models.CharField(blank=True, help_text='Inscrição estadual, municipal ou outro identificador fiscal.', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_tokens',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tokens bloqueados temporariamente (ex: em análise de saque).', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('COMMON', 'Common User'), ('COMPANY', 'Company'), ('STAFF', 'Staff'), ('ANALYST', 'Analyst'), ('ADMIN', 'Admin')], default='COMMON', help_text='Tipo de usuário (define comportamento e permissões).', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Endereço da carteira blockchain do usuário.', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
