# Generated by Django 4.2.21 on 2025-06-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_commonuser_company_user_blocked_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='CommonUser',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
