# Generated by Django 4.2.22 on 2025-06-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractedplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracted_plans', to='companies.company'),
        ),
        migrations.AddField(
            model_name='contractedplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan'),
        ),
    ]
