# Generated by Django 4.2.22 on 2025-06-09 01:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='PENDING', max_length=10)),
                ('tx_type', models.CharField(choices=[('REWARD', 'Recompensa'), ('WITHDRAW', 'Saque')], default='REWARD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, help_text='Endereço da carteira blockchain do usuário.', max_length=42, null=True)),
                ('blockchain_balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), help_text='Saldo na blockchain', max_digits=20)),
                ('virtual_balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), help_text='Saldo local antes de mintar tokens', max_digits=20)),
            ],
        ),
    ]
