# Generated by Django 4.2.22 on 2025-06-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='contracted_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='plans.contractedplan'),
        ),
    ]
