# Generated by Django 4.2.22 on 2025-06-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractedPlan',
            new_name='Contracted_Plan',
        ),
    ]
