# Generated by Django 4.2.22 on 2025-06-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_slug'),
        ('missions', '0004_mission_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='companies.company'),
            preserve_default=False,
        ),
    ]
