# Generated by Django 4.2.22 on 2025-06-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
    ]
