# Generated by Django 4.2.22 on 2025-06-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_fill_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
