# Generated by Django 4.2.22 on 2025-06-09 01:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=36)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
